apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  backupTargetName: "default"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
