apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: phpmyadmin-basic-auth
  namespace: wordpress
spec:
  encryptedData:
    auth: AgAdS1VtLXMW5SjSA+lfzl5LpTeu4UmZKYvgtVb9tKZwDSrzHnrun02mKt2j8xjJj2spvThaAQ/0eucevyi3FCUoktetl5jxldem2mZPSpEbHr22SqAcEO71IL2Twh8/pS8kJxHFP8WxV4FzcQsZwDcmJOPAcDo3r2jWbNipQ/iJhFrXoSdn3jXKbQ2VOmLu5JmTmhK5m/XhtCZhd5Rvvxmx6OB9eV0Z7h5iLiG50ZixWHJ4aIIkGe5aWFJrNQbPXFRZZgXGak3B6gmJbv1jb1Ct0nSUfJtMmiEReMtk28DACMyjR60SleGH7aNPevTcapulsJnW9+/1i5crxrYZQpiY/wErjrtVWsZiAA1O6vONmgAXA7jM6BcODOV4fP4v2R/PtjEjGa05h8lVPxXMExcW1Lwa7Sb8xMPckSJ6wP7MW7DmR1Kwu+Kc0jTVXzMgJM/nU2R6Nq3HV8W2zuKHpt3y4XYm6xR+0SnFXGj30x4k88sr8jgwft/suCupd6xZNmFyQqxp2ALpWnH8SlgF5slJAM7aLV3peGZtt5MOliuoWPUUeLpb6alWIqA3ogwPg9GWGBKNs4n7FkMjsH4KhkqibEDBmkyCVE2EkM7A/MAGqOotS0iIdHKic23Ftv0haKXt3XeQXvgwWN+R5kIuph8Hp/IUcMyHJlBdFAzflaiphbgfSK42lPGe4Z4Pn1SSwBGJYHVS1G7GencWwfEhJ79riJuTcMJXAke4lwty2AL3E57VUH8/xzXvlmc/UQFtD/SVWTWfGSc=
  template:
    metadata:
      name: phpmyadmin-basic-auth
      namespace: wordpress